services:
  postgres:
    image: postgres:16-alpine
    container_name: code-connect-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: codeconnect
      POSTGRES_PASSWORD: codeconnect
      POSTGRES_DB: codeconnect
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
